//package new_test.java;
//
//import java.util.*;
//
///*
// * This Java source file was generated by the Gradle 'init' task.
// */
//package new_test.java;

//public class AppTest {
//    @Test void appHasAGreeting() {
//        App classUnderTest = new App();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//
//    }
//}
