/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.java.bitcamp;

public class test1 {
  public static void main(String[] args) {
    System.out.println("test1");
  }

}